### ISSUE TITLE
error on grader

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#105]
Just checked the running grader and saw lots of these:

```
/home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:69:in `fetch_files!': undefined method `inject' for "":String (NoMethodError)
        from /home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_ruby.rb:135:in `get_submission'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:19:in `next_submission_with_assignment'
        from /home/ubuntu/rag/lib/submission/polling.rb:18:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
run_autograder.rb:10: warning: class variable access from toplevel
run_autograder exited. 
/home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:69:in `fetch_files!': undefined method `inject' for "":String (NoMethodError)
        from /home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_ruby.rb:135:in `get_submission'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:19:in `next_submission_with_assignment'
        from /home/ubuntu/rag/lib/submission/polling.rb:18:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
```

**Comment by tansaku** [comment]
restarting the grader to see the effect

**Comment by tansaku** [comment]
got same again on submission of a random ruby file on the berkeley SPOC HW1 intro:

```
one
run_autograder.rb:10: warning: class variable access from toplevel
run_autograder exited. 
/home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:69:in `fetch_files!': undefined method `inject' for "":String (NoMethodError)
        from /home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_ruby.rb:135:in `get_submission'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:19:in `next_submission_with_assignment'
        from /home/ubuntu/rag/lib/submission/polling.rb:18:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
```

**Comment by tansaku** [comment]
getting same with one of the sample solutions - hmm, this looks like an xqueue issue - I wonder if something on edX has just changed ...

**Comment by tansaku** [comment]
I can confirm this is failing on other SPOCs and also on the old grader with this error:

```
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/json/common.rb:148:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/json/common.rb:148:in `new'
        from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/json/common.rb:148:in `parse'
        from /home/ubuntu/rag/lib/edx_controller.rb:112:in `get_submission'
        from /home/ubuntu/rag/lib/edx_client.rb:281:in `block in each_submission'
        from /home/ubuntu/rag/lib/edx_client.rb:270:in `each'
        from /home/ubuntu/rag/lib/edx_client.rb:270:in `each_submission'
        from /home/ubuntu/rag/lib/edx_client.rb:50:in `run'
        from ./run_edx_client.rb:9:in `<main>'
```

so looks like the xqueue interface has changed somehow
