### ISSUE TITLE
bugs on master

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#117]
```
[tansaku@Samuels-MBP:~/Documents/Github/saasbook/rag (master)]$ 
→ bundle exec rspec
.......F....*.*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Submission::Xqueue it can create an assignment from a submission and grade it should pass assignment and submission to the autograder
     # run in a separate thread to avoid infinite loop
     Failure/Error: expect(true).to be_false
       expected true to respond to `false?` or perhaps you meant `be false` or `be_falsey`
     # ./spec/submission/xqueue_spec.rb:39:in `block (3 levels) in <top (required)>'

  2) Submission::Xqueue when there is no submission in queue it should sleep when
     # run in seperate thread to avoid infinite loop
     Failure/Error: expect(true).to be_false
       expected true to respond to `false?` or perhaps you meant `be false` or `be_falsey`
     # ./spec/submission/xqueue_spec.rb:56:in `block (3 levels) in <top (required)>'

Failures:

  1) Graders::RspecGrader should be able to grade a simple homework gives points to a hw1 solution
     Failure/Error: expect(b[:raw_score]).to be == 30
     
       expected: == 30
            got:    0
     # ./spec/graders/rspec_grader_spec.rb:20:in `block (3 levels) in <top (required)>'

Finished in 0.57171 seconds (files took 1.13 seconds to load)
15 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/graders/rspec_grader_spec.rb:18 # Graders::RspecGrader should be able to grade a simple homework gives points to a hw1 solution

Coverage report generated for RSpec to /Users/tansaku/Documents/GitHub/saasbook/rag/coverage. 356 / 942 LOC (37.79%) covered.
[tansaku@Samuels-MBP:~/Documents/Github/saasbook/rag (master)]$ 
→ bundle exec cucumber
..
Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /var/folders/2z/kh7rq7jn5l3gpbldyfg1tb4c0000gn/T/spec_file20170927-45695-1ivzqz1:26:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
........F..................................

(::) failed steps (::)

expected: == 100.0
     got:    0.0 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/adapter_x_queue_steps.rb:76:in `/^I should receive a grade of "(.*?)" for my assignment$/'
features/autograder_xqueue_stubbed.feature:17:in `Then I should receive a grade of "100" for my assignment'

Failing Scenarios:
cucumber features/autograder_xqueue_stubbed.feature:13 # Scenario: student submits a HerokuGrader homework

11 scenarios (1 failed, 10 passed)
45 steps (1 failed, 44 passed)
2m38.224s
```

**Comment by tansaku** [comment]
I think the latter is due to a heroku instance going offline - the better fix would be not relying on remote services, but I can make a quick fix by using my own heroku instance I think ...

**Comment by tansaku** [comment]
can't understand the rspec issue - running the fixture directly against the fixture spec gives the expected output:

```
[tansaku@Samuels-MBP:~/Documents/Github/saasbook/rag (117_bugs_on_master)]$ 
→ rspec -r ./spec/fixtures/ruby_intro_part1.rb  ./spec/fixtures/ruby_intro_part1_spec.rb

Ruby intro part 1
  #sum
    should be defined
    returns correct sum [20 points]
    works on the empty array [10 points]
  #max_2_sum
    should be defined
    returns the correct sum [7 points] (FAILED - 1)
    works even if 2 largest values are the same [3 points] (FAILED - 2)
    returns zero if array is empty [10 points] (FAILED - 3)
    returns value of the element if just one element [10 points] (FAILED - 4)
  #sum_to_n
    should be defined
    returns the correct sum [30 points] (FAILED - 5)
    returns false for the empty array with nonzero argument [5 points] (FAILED - 6)
    returns true for the empty array with zero argument [5 points] (FAILED - 7)

Failures:

  1) Ruby intro part 1 #max_2_sum returns the correct sum [7 points]
     Failure/Error: expect(max_2_sum([1,2,3,4,5])).to be_a_kind_of Fixnum
       expected nil to be a kind of Fixnum
     # ./spec/fixtures/ruby_intro_part1_spec.rb:26:in `block (3 levels) in <top (required)>'

  2) Ruby intro part 1 #max_2_sum works even if 2 largest values are the same [3 points]
     Failure/Error: expect( max_2_sum([1,2,3,3])).to eq 6
     
       expected: 6
            got: nil
     
       (compared using ==)
     # ./spec/fixtures/ruby_intro_part1_spec.rb:30:in `block (3 levels) in <top (required)>'

  3) Ruby intro part 1 #max_2_sum returns zero if array is empty [10 points]
     Failure/Error: expect(max_2_sum([])).to be_zero
       expected nil to respond to `zero?`
     # ./spec/fixtures/ruby_intro_part1_spec.rb:33:in `block (3 levels) in <top (required)>'

  4) Ruby intro part 1 #max_2_sum returns value of the element if just one element [10 points]
     Failure/Error: expect(max_2_sum([3])).to eq 3
     
       expected: 3
            got: nil
     
       (compared using ==)
     # ./spec/fixtures/ruby_intro_part1_spec.rb:36:in `block (3 levels) in <top (required)>'

  5) Ruby intro part 1 #sum_to_n returns the correct sum [30 points]
     Failure/Error: expect(sum_to_n?([1,2,3,4,5], 5)).to be_true
       expected nil to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/fixtures/ruby_intro_part1_spec.rb:45:in `block (3 levels) in <top (required)>'

  6) Ruby intro part 1 #sum_to_n returns false for the empty array with nonzero argument [5 points]
     Failure/Error: expect(sum_to_n?([], 1)).to be_false
       expected nil to respond to `false?` or perhaps you meant `be false` or `be_falsey`
     # ./spec/fixtures/ruby_intro_part1_spec.rb:50:in `block (3 levels) in <top (required)>'

  7) Ruby intro part 1 #sum_to_n returns true for the empty array with zero argument [5 points]
     Failure/Error: expect(sum_to_n?([], 0)).to be_true
       expected nil to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/fixtures/ruby_intro_part1_spec.rb:53:in `block (3 levels) in <top (required)>'

Finished in 0.0215 seconds (files took 0.09975 seconds to load)
12 examples, 7 failures

Failed examples:

rspec ./spec/fixtures/ruby_intro_part1_spec.rb:25 # Ruby intro part 1 #max_2_sum returns the correct sum [7 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:29 # Ruby intro part 1 #max_2_sum works even if 2 largest values are the same [3 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:32 # Ruby intro part 1 #max_2_sum returns zero if array is empty [10 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:35 # Ruby intro part 1 #max_2_sum returns value of the element if just one element [10 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:44 # Ruby intro part 1 #sum_to_n returns the correct sum [30 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:49 # Ruby intro part 1 #sum_to_n returns false for the empty array with nonzero argument [5 points]
rspec ./spec/fixtures/ruby_intro_part1_spec.rb:52 # Ruby intro part 1 #sum_to_n returns true for the empty array with zero argument [5 points]


```

**Comment by tansaku** [comment]
okay, so https://github.com/saasbook/rag/commit/79215f6492f4e3b2cc1699625d348e3dbf0b04b5 breaks that spec - looks like when I changed the fixture from rspec 2 to 3 syntax ...

**Comment by tansaku** [comment]
so the issue was the submissons directory caching test cases and the current rspecs getting confused by the new set up where we include `/**/*.rb` from the students submitted directory, which is a separate dir for the live grader, but the rspec tests just default to the entire submissions directory ...
