### ISSUE TITLE
Difficulties grading Oracle of Bacon assignment

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#57]
Not working in live deployment, need cucumber tests to check we can grade this, maybe ...

**Comment by tansaku** [comment]
So I've been wrestling with this for a few days.   Here's what I've done and what I've learnt:

1) I've created https://github.com/saasbook/hw-oracle-of-bacon-ci which has an updated spec including the new gems rspec-its and rspec-collection_matchers, to cope with the legacy rspec elements in the assignment

2) I'm working against the staging grader and I've found that to avoid getting errors like "cannot load such file -- rspec/collection_matchers" I've had to add all the OoB related gems to the rag Gemfile, which I can do, but would make it diffcult for those without access to the grader to develop homeworks that involve additional gems

3) I've been deleting ~/rag/submissions/assignment1.5-spec/oracle_of_bacon_spec.rb to ensure that the grader is using the correct spec file but I notice that if I only delete oracle_of_bacon_spec.rb I get the following error

```
at_exit hook called
/home/ubuntu/.rvm/gems/ruby-2.2.2/bundler/gems/xqueue-ruby-ed709d6b395a/lib/xqueue_ruby/xqueue_submission.rb:61:in `grade!': no implicit conversion of nil into String (TypeError)
        from /home/ubuntu/rag/lib/submission/base.rb:22:in `handle_submission'
        from /home/ubuntu/rag/lib/submission/polling.rb:19:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
```

but that I can fix that by ensuring that I remove the whole directory:

```
rmdir ~/rag/submissionsassignment1.5-spec/
```

This is somewhat worrying is that it seems to make it difficult to deploy a new grading rubric unless one has direct access to the grader

4) I tested all this on the staging grader, and get grading appearing in the rag logs, but the results are not getting back to edX, but I can now see the big error as the system not being able to load the related OoB XML files:

```
1) OracleOfBacon parsing XML response for unauthorized access/invalid API key type
     Failure/Error: subject { OracleOfBacon::Response.new(File.read 'unauthorized_access.xml') }
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - unauthorized_access.xml 
```

I can probably hack a solution by adding the XML files to the correct root relative place on the grader as a temporary fix. Fingers crossed that works and that we get output back to edX or we may have to fall back to the old grader ...?

If you have any input on any of the above - in particular a good way to have the OoB spec load the necessary XML files that will work well with the current grader configuration I am all ears!

**Comment by tansaku** [comment]
So copying the OoB xml files from the downloaded location to an 'autograder' folder on the grader server provided a temporary fix to allow the grader to operate on the OoB spec:

```
cp submissions/assignment1.5-spec/*.xml autograder/
```

Grader is now working in production with OoB spec, but have created issues related to the three sticking points encountered: #58, #59, #60
