### ISSUE TITLE
HW4 Test Not Working? 

### ISSUE THREAD

**Issue by zhangaaron** [saasbook/rag#86]
Appears that the HW4 cucumber test is not working as intended. I'm unsure when this happened, or if this is an issue with the fact that we are running a Cucumber test suite within a Cucumber test suite and some environment variables are being reset during the test run. I seem to recall having some of these issues over the summer but I don't recall how I solved it, if I did. It hasn't been showing up on Travis because Travis doesn't run these tests, and the other tests don't have the problem since it doesn't get to running the Cucumber features. @tansaku, have you run into this issue during running the test suite? 

```
 bundle exec cucumber features/autograder_xqueue_stubbed.feature:47
Feature: Autograder configured to accept student submissions from edX and grade them
  As an instructor
  So that I can give feedback to my students on their code responses
  I want to be able to create a code submission page in edX and grade it using rag

  @require_net_connect
  Scenario: student submits a HW4                                      # features/autograder_xqueue_stubbed.feature:47
    Given I set up a test that requires internet connection            # features/step_definitions/adapter_x_queue_steps.rb:24
    Given an XQueue that has submission "hw4_submission.json" in queue # features/step_definitions/adapter_x_queue_steps.rb:28
      ["http://www.fakedownload.com/hw4.zip"]
      register_uri for : http://www.fakedownload.com/hw4.zip
    And has been setup with the config file "conf.yml"                 # features/step_definitions/adapter_x_queue_steps.rb:44
/media/aaron/why/sum2015/rag/lib/graders/feature_grader/lib/HW4feature.rb:151:in `rescue in run!': invalid cucumber results["Disabling profiles...\n", "\n", " *** ERROR: #<SystemExit: exit> *** \n", "Run options: --seed 35036\n", "\n", "# Running:\n", "\n", "\n", "\n", "Finished in 0.001925s, 0.0000 runs/s, 0.0000 assertions/s.\n", "\n", "0 runs, 0 assertions, 0 failures, 0 errors, 0 skips\n"] (StandardError)
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/lib/HW4feature.rb:161:in `run!'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/lib/HW4feature.rb:45:in `block in total'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/lib/HW4feature.rb:42:in `each'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/lib/HW4feature.rb:42:in `total'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:242:in `check_ref_cucumber'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:109:in `block (2 levels) in runner_block'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:332:in `time_operation'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:105:in `block in runner_block'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:76:in `chdir'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:76:in `runner_block'
	from /media/aaron/why/sum2015/rag/lib/auto_grader.rb:73:in `call'
	from /media/aaron/why/sum2015/rag/lib/auto_grader.rb:73:in `block in run_in_subprocess'
	from /media/aaron/why/sum2015/rag/lib/auto_grader.rb:69:in `fork'
	from /media/aaron/why/sum2015/rag/lib/auto_grader.rb:69:in `run_in_subprocess'
	from /media/aaron/why/sum2015/rag/lib/graders/feature_grader/hw4_grader.rb:55:in `grade'
	from /media/aaron/why/sum2015/rag/lib/submission/base.rb:20:in `handle_submission'
	from /media/aaron/why/sum2015/rag/lib/submission/polling.rb:19:in `block in run'
	from /media/aaron/why/sum2015/rag/lib/submission/polling.rb:17:in `loop'
	from /media/aaron/why/sum2015/rag/lib/submission/polling.rb:17:in `run'
	from /media/aaron/why/sum2015/rag/features/step_definitions/adapter_x_queue_steps.rb:53:in `block (3 levels) in <top (required)>'
Submission message after grade: Your submission was recorded at 2010-06-19 18:52:28 -0700 : submission is on time.
Score: 0/100
There was a fatal error with your submission. It either timed out or caused an exception.
    Then I should receive a grade of "100" for my assignment           # features/step_definitions/adapter_x_queue_steps.rb:49
      expected: == 100.0
           got:    0.0 (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/adapter_x_queue_steps.rb:57:in `/^I should receive a grade of "(.*?)" for my assignment$/'
      features/autograder_xqueue_stubbed.feature:51:in `Then I should receive a grade of "100" for my assignment'

Failing Scenarios:
cucumber features/autograder_xqueue_stubbed.feature:47 # Scenario: student submits a HW4

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m16.693s

```

**Comment by tansaku** [comment]
@zhangaaron I don't think I've ever seen this failure locally ...

**Comment by tansaku** [comment]
@zhangaaron where are you getting this?  on master? what's your local setup?

**Comment by tansaku** [comment]
that particular test passes fine for me at the latest commit on master:

```
54b5b06 2016-03-02 | Merge pull request #82 from saasbook/67_hw4_grader_freeze (HEAD -> master, origin/master, origin/HEAD) [Aaron]
```

**Comment by zhangaaron** [comment]
Perhaps my environment, I'll investigate it.

**Comment by tansaku** [comment]
@zhangaaron let me know what you find.  Ultimately to best support other open source developers getting involved in this we want (as you know) to remove all environmental dependencies with appropriate sandboxing etc.

**Comment by zhangaaron** [comment]
still not sure exactly why error occured, but moving the project off my external hard drive onto primary drive fixed it. I agree with that sentiment but I think this is more of an issue with cucumber than anything else
