### ISSUE TITLE
Legacy HW1 grader reported spinning

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#96]
logged in to the grader and saw this error:

```
Submission message after grade: Your submission was recorded at 2016-04-06 04:41:05 +0000 : submission is on time.
Score: 1.0/1.0
--------------------------------------------------------------------------------
Test passed. (+0.2)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.25)
--------------------------------------------------------------------------------
Test passed. (+0.25)
Total score: 1.0 / 1.0
Completed in 35.455482645 seconds.
Cloning into 'temp_repo'...
remote: Counting objects: 10, done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 10
Receiving objects: 100% (10/10), done.
Checking connectivity... done.
run_autograder.rb:10: warning: class variable access from toplevel
run_autograder exited. 
/home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `local': argument out of range (ArgumentError)
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `make_time'
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:364:in `parse'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:14:in `create_time_bracket'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `block in initialize'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `each'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `map'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `initialize'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:21:in `new'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:21:in `next_submission_with_assignment'
        from /home/ubuntu/rag/lib/submission/polling.rb:18:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
```

**Comment by tansaku** [comment]
last thing in log file was this:

```
D, [2016-04-06T04:45:27.590641 #13769] DEBUG -- : Download from repo spec file to: submissions/assignment3-spec
I, [2016-04-06T04:45:27.602421 #13769]  INFO -- : XQueue adapter received submission. Student b37b96119b2275939815f8570b8a6185 assignment assignment3
D, [2016-04-06T04:45:27.608628 #13769] DEBUG -- : Start subprocess to run student code.
D, [2016-04-06T04:46:03.272520 #13769] DEBUG -- : submission message = Your submission was recorded at 2016-04-06 04:41:05 +0000 : submission is on time.
Score: 1.0/1.0
--------------------------------------------------------------------------------
Test passed. (+0.2)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.075)
--------------------------------------------------------------------------------
Test passed. (+0.25)
--------------------------------------------------------------------------------
Test passed. (+0.25)
Total score: 1.0 / 1.0
Completed in 35.455482645 seconds.
D, [2016-04-06T07:22:32.414323 #13769] DEBUG -- : Grader payload: {"assignment_name"=>"assignment5-legacy-bugfix",
 "assignment_spec_uri"=>
  "git@github.com:saasbook/hw-refactoring-legacy-code-bug-fix-ci.git",
 "autograder_type"=>"HW5Grader",
 "due_dates"=>{"2016-016-30"=>1.0, "2016-06-06"=>0.75}}

D, [2016-04-06T07:22:32.626782 #13769] DEBUG -- : Download from repo spec file to: submissions/assignment5-legacy-bugfix-spec

```

**Comment by tansaku** [comment]
I tried submitting Legacy HW1 reference solution to https://edge.edx.org/courses/course-v1:SUNY_Binghamton+CS445-2-S16+2016_Spring/courseware/64746ad0f2b84ce2af1f1b627c735866/ec766c87cbc7467b9a693078eb78d2c8/ and it span for five minutes so I restarted the grader

**Comment by tansaku** [comment]
this is the XML for that submission element:

```xml
<problem>
  <coderesponse queuename="cs169-rev-production">
    <filesubmission points="100"/>
    <codeparam>
      <grader_payload>
      {"assignment_name": "assignment5-legacy-bugfix",
      "assignment_spec_uri": "git@github.com:saasbook/hw-refactoring-legacy-code-bug-fix-ci.git",
      "autograder_type": "HW5Grader",
      "due_dates": {"2016-016-30": 1.0, "2016-06-06": 0.75}
      }
      </grader_payload>
    </codeparam>
  </coderesponse>
</problem>
```

and I notice a mis-formatting in the due dates ...

**Comment by tansaku** [comment]
I fixed that issue, re-published, re-started the grader and resubmitted. Then saw this error in the grader output:

```
/home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `local': argument out of range (ArgumentError)
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:300:in `make_time'
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/time.rb:364:in `parse'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:14:in `create_time_bracket'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `block in initialize'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `each'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `map'
        from /home/ubuntu/rag/lib/assignment/xqueue.rb:36:in `initialize'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:21:in `new'
        from /home/ubuntu/rag/lib/submission/xqueue.rb:21:in `next_submission_with_assignment'
        from /home/ubuntu/rag/lib/submission/polling.rb:18:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
```

**Comment by tansaku** [comment]
so I think the date was still invalid.  See http://stackoverflow.com/questions/800118/ruby-time-parse-gives-me-out-of-range-error - now that I changed the due dates like so:

```json
"due_dates": {"2016-06-30": 1.0, "2016-06-06": 0.75}
```
i.e. with a valid month the grader seems to work normally: 

![](https://www.dropbox.com/s/3g9jnik8vclgwbx/Screenshot%202016-04-06%2008.35.57.png?dl=1)

**Comment by tansaku** [comment]
So the action item here then is to make the grader handle this failure state a little more gracefully ...
