### ISSUE TITLE
grader down (reported for HW4)

### ISSUE THREAD

**Issue by tansaku** [saasbook/rag#98]
@rilson17 reports the grader is down.  I see the following in the grader direct output in tmux:

```
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:360:in `require_or_load'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:184:in `const_missing'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:184:in `const_missing'
/home/ubuntu/rag/submissions/a55eec8354504b64f3d70a7448f3e045/assignment4/2016-05-03-18-26-57/db/migrate/20120130161449_add_more_movies.rb:16:in `block in up'
/home/ubuntu/rag/submissions/a55eec8354504b64f3d70a7448f3e045/assignment4/2016-05-03-18-26-57/db/migrate/20120130161449_add_more_movies.rb:15:in `each'
/home/ubuntu/rag/submissions/a55eec8354504b64f3d70a7448f3e045/assignment4/2016-05-03-18-26-57/db/migrate/20120130161449_add_more_movies.rb:15:in `up'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:608:in `exec_migration'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `block in ddl_transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:1040:in `ddl_transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:93:in `popen3'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:152:in `block in setup_rails_app'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:151:in `each'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:151:in `setup_rails_app'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:82:in `block (2 levels) in runner_block'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:336:in `time_operation'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:81:in `block in runner_block'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:76:in `chdir'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:76:in `runner_block'
        from /home/ubuntu/rag/lib/auto_grader.rb:73:in `call'
        from /home/ubuntu/rag/lib/auto_grader.rb:73:in `block in run_in_subprocess'
        from /home/ubuntu/rag/lib/auto_grader.rb:69:in `fork'
        from /home/ubuntu/rag/lib/auto_grader.rb:69:in `run_in_subprocess'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:55:in `grade'
        from /home/ubuntu/rag/lib/submission/base.rb:20:in `handle_submission'
        from /home/ubuntu/rag/lib/submission/polling.rb:19:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
Submission message after grade: Your submission was recorded at 2016-05-03 18:21:38 +0000 : submission is on time.
Score: 0/100
There was a fatal error with your submission. It either timed out or caused an exception.
```

**Comment by tansaku** [comment]
and the following in what I think is the last log:

```

 *** ERROR: #<SystemExit: exit> *** 
Coverage report generated for Cucumber Features, RSpec to /home/ubuntu/rag/submissions/5bd52d4d196edb18abc150eea811d6c4/assignment4/2016-05-03-18-02-06/coverage. 39 / 51 LOC (76.47%) covered.
Test passed. (+0.5)
----------------------------------------
  2 out of 3 scenarios passed
  Score: 26/40
----------------------------------------
Total score: 66.0 / 100.0
Completed in 33.457280539 seconds.
D, [2016-05-03T18:24:18.113534 #28699] DEBUG -- : Grader payload: {"assignment_name"=>"assignment4",
 "assignment_spec_uri"=>"git@github.com:saasbook/hw-bdd-tdd-cycle-ci.git",
 "autograder_type"=>"HW4Grader",
 "due_dates"=>{"2016-12-21"=>1.0, "2100-12-28"=>0.75}}

D, [2016-05-03T18:24:18.787393 #28699] DEBUG -- : Download from repo spec file to: submissions/assignment4-spec
I, [2016-05-03T18:24:18.791293 #28699]  INFO -- : XQueue adapter received submission. Student a55eec8354504b64f3d70a7448f3e045 assignment assignment4
D, [2016-05-03T18:24:18.828719 #28699] DEBUG -- : Start subprocess to run student code.
D, [2016-05-03T18:24:24.990570 #28699] DEBUG -- : submission message = Your submission was recorded at 2016-05-03 18:19:03 +0000 : submission is on time.
Score: 0/100
There was a fatal error with your submission. It either timed out or caused an exception.
D, [2016-05-03T18:26:57.714713 #28699] DEBUG -- : Grader payload: {"assignment_name"=>"assignment4",
 "assignment_spec_uri"=>"git@github.com:saasbook/hw-bdd-tdd-cycle-ci.git",
 "autograder_type"=>"HW4Grader",
 "due_dates"=>{"2016-12-21"=>1.0, "2100-12-28"=>0.75}}

D, [2016-05-03T18:26:57.907975 #28699] DEBUG -- : Download from repo spec file to: submissions/assignment4-spec
I, [2016-05-03T18:26:57.914151 #28699]  INFO -- : XQueue adapter received submission. Student a55eec8354504b64f3d70a7448f3e045 assignment assignment4
D, [2016-05-03T18:26:57.961396 #28699] DEBUG -- : Start subprocess to run student code.
```

**Comment by tansaku** [comment]
okay, trying in @rilson17's SPOC I get:

```Unable to deliver your submission to grader (Reason: unexpected HTTP status code [500]). Please try again later.```

**Comment by tansaku** [comment]
I'm getting the same issue on the main MOOC too:

```
Unable to deliver your submission to grader (Reason: unexpected HTTP status code [500]). Please try again later.
```

**Comment by tansaku** [comment]
edX made a change that fixed this after we escalated it
